name: Run Tests

on:
  pull_request:
    branches:
      - main  # Alvo de pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # ou a versão que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
