name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a versão que você deseja

      - name: Install dependencies
        run: npm install

      - name: Run lint (code quality)
        run: npm run lint

      - name: Run tests
        run: npm test
